---
apiVersion: v1
kind: Deployment
metadata:
  name: date-app-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: date-app
  replicas: 3 
  template:
    metadata:
      labels:
        app: date-app
    spec:
      containers:
      - name: date-app-container
        image: gcr.io/$GOOGLE_CLOUD_PROJECT/date-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: date-app
  namespace: default
  labels:
    app: date-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: date-app
  type: LoadBalancer